// Exceptions in Dart
void main() {
  print('Hello, Dart!');
  // // Coming soon: exceptions...
  // if (astronauts == 0) {
  //   throw StateError('No astronauts.');
  // }

  // // Coming soon: exceptions...
  // Future<void> describeFlybyObjects(List<String> flybyObjects) async {
  //   try {
  //     for (final object in flybyObjects) {
  //       var description = await File('$object.txt').readAsString();
  //       print(description);
  //     }
  //   } on IOException catch (e) {
  //     print('Could not describe object: $e');
  //   } finally {
  //     flybyObjects.clear();
  //   }
  // }
}
